# Generated by Django 5.1.5 on 2025-01-22 09:01

import datetime
import django.db.models.deletion
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.BooleanField(default=False, verbose_name='Desactivado')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=12, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('address', models.TextField(default='', null=True, verbose_name='Dirección')),
                ('observations', models.TextField(default='', null=True, verbose_name='Observaciones')),
                ('qr', models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_form_qr, verbose_name='QR')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='', max_length=20, verbose_name='PIN')),
                ('dni', models.CharField(default='', max_length=20, verbose_name='DNI')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Terminada')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 1, 47, 637492), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 1, 47, 637517), null=True, verbose_name='Fin')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.client', verbose_name='Client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
