# Generated by Django 5.1.5 on 2025-01-24 09:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2025, 1, 24, 9, 10, 11, 680579), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 1, 24, 9, 10, 11, 680615), null=True, verbose_name='Fin')),
                ('notes', models.TextField(default='', null=True, verbose_name='Notas')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.employee', verbose_name='Empleado')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicestatus', verbose_name='Estado')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.DeleteModel(
            name='Assistance',
        ),
    ]
