# Generated by Django 5.1.5 on 2025-01-24 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_servicestatus_servicetype_service_delete_assistance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='color',
            field=models.CharField(default='', max_length=10, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 11, 33, 1, 336511), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 11, 33, 1, 336441), null=True, verbose_name='Inicio'),
        ),
    ]
