# Generated by Django 5.1.5 on 2025-02-09 21:45

import datetime
import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_servicestatus_options_servicestatus_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='emp_notes',
            field=models.TextField(default='', null=True, verbose_name='Notas del empleado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='gestion.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='gestion.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 21, 44, 59, 860784), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 21, 44, 59, 860719), null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='color',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Color'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_service_img, verbose_name='Image')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion.servicetype', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imagen del Servicio',
                'verbose_name_plural': 'Imagenes de los Servicios',
            },
        ),
    ]
