# Generated by Django 5.1.5 on 2025-02-09 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_service_emp_notes_alter_service_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 22, 25, 31, 773750), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 22, 25, 31, 773708), null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion.service', verbose_name='Servicio'),
        ),
    ]
